config/routes.rb
Rails.application.routes.draw do
  get 'teams/new'
  get 'teams/edit'
  get 'players/new'
  get 'sessions/new'
  get 'users/new'
  get 'matches/new'

  root 'static_pages#home'
  get 'league' => 'static_pages#league'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'admin' => 'static_pages#admin'
  get 'scores' => 'static_pages#scores'
  get 'playerlist' => 'players#playerlist'
  get 'newscore' => 'player_scores#new'
  post 'newscore' => 'player_scores#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    resources :teams
  end
  
  resources :players
  resources :matches

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	before_action :is_admin, only: [:admin]

  def home
  end

  def league
  	@users = User.all
  end

  def admin
  end

  def scores
  	@players = Player.all
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<%= link_to "Add player", new_player_path %><br />
<%= link_to "See all players", playerlist_path %><br />
<%= link_to "Create new match", new_match_path %><br />
<%= link_to "Edit matches", matches_path %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1> Välkommen till SK IT Fantasy</h1>

	<h2>Här kommer det snart finnas massa godsaker</h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/league.html.erb
<% provide(:title, "Fantasy league") %>

<h1>Current status in fantasy league</h1>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<table class="table">
			<thead>
				<tr>
					<td><strong>Lagnamn</strong></td>
					<td><strong>Poäng</strong></td>
				</tr>
			<% @users.each do |user| %>
				<tr>
					<td><%= link_to user.team.name, user %></td>
					<td><%= user.team.get_points %></td>
				</tr>
			</thead>
			<% end %>
		</table>
	</div>
</div>

app/views/static_pages/scores.html.erb
<% provide(:title, "Poängliga") %>

<h1>Intern poängliga</h1>

<div class="row">
	<div class="col-md-9 col-md-offset-1">
		<table id="scorestable" class="table">
			<thead>
				<tr>
					<td></td>
					<td>Games</td>
					<td>Goals</td>
					<td>Assists</td>
					<td>Pos</td>
					<td>Neg</td>
					<td>Penalties</td>
					<td>MVP's</td>
					<td>Total</td>
				</tr>
			</thead>
			<tbody>
				<% @players.each do |player| %>
				<tr>
					<td><%= player.name %></td>
					<td><%= PlayerScore.where(player_id: player.id).sum(:games) %></td>
					<td><%= PlayerScore.where(player_id: player.id).sum(:goals) %></td>
					<td><%= PlayerScore.where(player_id: player.id).sum(:assists) %></td>
					<td><%= PlayerScore.where(player_id: player.id).sum(:pos) %></td>
					<td><%= PlayerScore.where(player_id: player.id).sum(:neg) %></td>
					<td><%= PlayerScore.where(player_id: player.id).sum(:penalties) %></td>
					<td><%= PlayerScore.where(player_id: player.id).sum(:mvp) %></td>
					<td><%= player.total_score %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>