config/routes.rb
Rails.application.routes.draw do
  get 'teams/new'
  get 'teams/edit'
  get 'players/new'
  get 'sessions/new'
  get 'users/new'
  get 'matches/new'

  root 'static_pages#home'
  get 'league' => 'static_pages#league'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'admin' => 'static_pages#admin'
  get 'scores' => 'static_pages#scores'
  get 'playerlist' => 'players#playerlist'
  get 'newscore' => 'player_scores#new'
  post 'newscore' => 'player_scores#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    resources :teams
  end
  
  resources :players
  resources :matches

end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :teams, through: :team_members
	has_many :team_members, dependent: :destroy
	has_many :matches, through: :player_score
	has_many :player_scores
	belongs_to :position

	validates :name, presence: true
	validates :desc, presence: true
	validates :price, presence: true
	validates :position_id, presence: true

	def total_score
		total = 0
    	total += PlayerScore.where(player_id: self.id).sum(:goals) * 3
    	total += PlayerScore.where(player_id: self.id).sum(:assists) * 2
    	total += PlayerScore.where(player_id: self.id).sum(:pos)
    	total -= PlayerScore.where(player_id: self.id).sum(:neg)
    	total -= PlayerScore.where(player_id: self.id).sum(:penalties)
    	total += PlayerScore.where(player_id: self.id).sum(:mvp) * 2
    	total
  	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :admin_user, only: [:edit, :destroy, :update]

  def new
  	@player = Player.new
  end

  def edit
    @player = Player.find(params[:id])
  end

  def show
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update_attributes(player_params)
      flash[:success] = "Player updated"
      redirect_to playerlist_path
    else
      render 'edit'
    end
  end

  def create
  	@player = Player.new(player_params)
  	if @player.save
      flash[:success] = "Player successfully added"
  		redirect_to new_player_path
  	else
  		flash[:danger] = "Something went wrong"
  		render 'new'
  	end
  end

  def playerlist
  	@players = Player.all
  end

  def destroy
    Player.find(params[:id]).destroy
    flash[:success] = "User deleted!"
    redirect_to playerlist_path
  end

  private

  	def player_params
  		params.require(:player).permit(:name, :desc, :price, :position_id)
  	end

    def admin_user
      unless current_user.admin?
        flash[:danger] = "Försvinn härifrån"
        redirect_to root_url
      end
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.html.erb
<% provide(:title, "Edit player") %>
<h1>Edit this player</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@player) do |f| %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :desc %>
			<%= f.text_field :desc, class: 'form-control' %>

			<%= f.label :position_id %>
			<%= f.collection_select(:position_id, Position.all, :id, :pos) %>

			<%= f.label :price %>
			<%= f.text_field :price, class: 'form-control' %>

			<%= f.submit "Save changes", class: 'btn btn-primary' %>
		<% end %>

	</div>
</div>

app/views/players/new.html.erb
<% provide(:title, "Add new player") %>
<h1>Add new player</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@player) do |f| %>

			<%= f.label :name%>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :desc, "Beskrivning" %>
			<%= f.text_field :desc, class: 'form-control' %>

			<%= f.label :position_id, "Position" %>
			<%= f.collection_select(:position_id, Position.all, :id, :pos) %>

			<%= f.label :price %>
			<%= f.text_field :price, class: 'form-control' %> 

			<%= f.submit "Lägg till spelaren", class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/players/playerlist.html.erb
<ul class="adminplayerlist">
	<% @players.each do |player| %>
		<li>
			<%= link_to player.name, player_path(player) %>
			<% unless !current_user.admin? %> 
				| <%= link_to "Edit", edit_player_path(player) %>
				| <%= link_to "Delete", player, method: :delete, data: { confirm: "You sure?" } %>
			<% end %>
		</li>
	<% end %>
</ul>