config/routes.rb
Rails.application.routes.draw do
  get 'teams/new'
  get 'teams/edit'
  get 'players/new'
  get 'sessions/new'
  get 'users/new'
  get 'matches/new'

  root 'static_pages#home'
  get 'league' => 'static_pages#league'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'admin' => 'static_pages#admin'
  get 'scores' => 'static_pages#scores'
  get 'playerlist' => 'players#playerlist'
  get 'newscore' => 'player_scores#new'
  post 'newscore' => 'player_scores#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    resources :teams
  end
  
  resources :players
  resources :matches

end

app/models/match.rb
class Match < ActiveRecord::Base
	has_many :players, through: :player_score
	has_many :player_scores
	accepts_nested_attributes_for :player_scores
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

	before_action :logged_in_user, only: [:new, :create, :edit]
	before_action :is_admin, only: [:new, :create, :edit]

	def new
		@players = Player.all
		@match = Match.new
	end

	def create
		match = Match.new(match_params)
		if match.save!
			flash[:success] = "Match created and added" 
		else 
			flash[:danger] = "Something went wrong"
		end
		redirect_to root_path
	end

	def index
		@matches = Match.all
	end

	def edit
		@match = Match.find(params[:id])
	end

	def update
		match = Match.find(params[:id])
		if match.save!
			match.update_attributes(update_params)
			flash[:success] = "Match updated"
		else
			flash[:danger] = "Something went wrong"
		end
		redirect_to root_path
	end

	def update_params
		params.require(:match).permit(:home_team, :away_team, :home_goal, :away_goal)
	end

	def match_params
		params.require(:match).permit(:home_team, :away_team, :home_goal, :away_goal, :date, player_scores_attributes: [:player_id, :games, :goals, :assists, :pos, :neg, :penalties, :mvp])
	end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/edit.html.erb
<h1>Update match</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">

<%= form_for(@match) do |f| %>
	<%= f.label :home_team %>
	<%= f.text_field :home_team %>

	<%= f.label :away_team %>
	<%= f.text_field :away_team %>

	<%= f.label :home_goal %>
	<%= f.text_field :home_goal %>

	<%= f.label :away_goal %>
	<%= f.text_field :away_goal %>

	<%= f.submit "Uppdatera match", class: "btn btn-primary" %>
<% end %>

</div>
</div>

app/views/matches/index.html.erb
<% provide(:title, "All matches") %>

<h1>All matches</h1>
<% @matches.each do |match| %>
	<h1><%= match.home_team %> - <%= match.away_team %> | <%= link_to "EDIT", edit_match_path(match) %></h1><br />
<% end %>

app/views/matches/new.html.erb
<% provide(:title, "New match") %>

<h1>New match</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@match) do |m| %>
		
		<center>
			<div class="field">
				<%= m.label :home_team %>
				<%= m.text_field :home_team %>
			</div>
			<div class="field">
				<%= m.label :away_team %>
				<%= m.text_field :away_team %>
			</div>
		</center>
		<br />

		<div id="reporttable">
			<table class="center" style="text-align: center">
				<thead class="center">
					<tr>
						<td></td>
						<td>Games</td>
						<td>Goals</td>
						<td>Asssists</td>
						<td>Pos</td>
						<td>Neg</td>
						<td>Penalties</td>
						<td>MVP</td>
					</tr>
				</thead>
				<tbody>

					<% @players.each do |player| %>
					
					<tr>
						
						<td><strong><%= player.name %></strong></td>

						<%= m.fields_for :player_scores, PlayerScore.new do |p| %>

						<td>
							<%= p.number_field :games, class: "numberinput center", value: "0" %>
						</td>

						<td>
							<!-- <%= p.label :goals, "Mål" %> -->
							<%= p.number_field :goals, class: "numberinput center", value: "0" %>
						</td>

						<td>
							<!-- <%= p.label :assists, "Assist" %> -->
							<%= p.number_field :assists, class: "numberinput center", value: "0" %>
						</td>

						<td>
							<!-- <%= p.label :pos, "Framåtmål" %> -->
							<%= p.number_field :pos, class: "numberinput center", value: "0" %>
						</td>

						<td>
							<!-- <%= p.label :neg, "Bakåtmål" %> -->
							<%= p.number_field :neg, class: "numberinput center", value: "0"  %>
						</td>

						<td>
							<%= p.number_field :penalties, class: "numberinput center", value: "0"  %>
						</td>

						<td>
							<!-- <%= p.label :mvp, "MVP" %> -->
							<%= p.number_field :mvp, class: "numberinput center", value: "0" %>
						</td>

						<%= p.hidden_field :player_id, value: player.id %>

						<%= p.hidden_field :date, value: Date.today %>

						<% end %>

					</tr>

					<% end %>
				</tbody>
			</table>
		</div>
		<br />

		<center>
			<div class="field">
				<%= m.label :home_goal, "Home team goals" %>
				<%= m.text_field :home_goal %>
			</div>
			<div class="field">
				<%= m.label :away_goal, "Away team goals" %>
				<%= m.text_field :away_goal %>
			</div>
		</center>
		<%= m.submit "Lägg till match", class: "btn btn-primary" %>

		<% end %>
	</div>
</div>