config/routes.rb
Rails.application.routes.draw do
  get 'teams/new'
  get 'teams/edit'
  get 'players/new'
  get 'sessions/new'
  get 'users/new'
  get 'matches/new'

  root 'static_pages#home'
  get 'league' => 'static_pages#league'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'admin' => 'static_pages#admin'
  get 'scores' => 'static_pages#scores'
  get 'playerlist' => 'players#playerlist'
  get 'newscore' => 'player_scores#new'
  post 'newscore' => 'player_scores#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    resources :teams
  end
  
  resources :players
  resources :matches

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Fantasy developed by Tim Lestander
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "League", league_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Fantasy", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "League", league_path %></li>
				<li><%= link_to "Poängliga", scores_path %></li>
				<% if logged_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li><%= link_to "Your team", user_team_path(current_user, current_user.team) %></li>
							<li class="divider"></li>
							<li><%= link_to "Log out", logout_path, method: "delete" %></li>
							<% if is_admin?(current_user) %>
								<li class="divider"></li>
								<li><%= link_to "Administrate", admin_path %></li>
							<% end %>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>